### PR TITLE
feat(child_process): add `spawn`

### PR DESCRIPTION
**Pull request by Massolari**
Just found this package and it's great for my Gleam application, it's just missing the `spawn` command from the `child_process` module, so I'm adding it here in this PR.
I'm also adding the type `ChildProcess`, but not with all the fields and methods it has, only those I need.

### CODE REVIEW

**Comment by CrowdHailer** [comment]
Hi, thanks for the PR.

I don't think that I want to introduce this (in my eyes) OO style interface where things like child process have fns attached.
Can we change this to a solution where there is a kill function that takes a child process as an argument

**Comment by lpil** [comment]
I agree RE the OOP API design, but I'd also like to say that this is an incorrect definition even if you want to use the OOP design. `child_process.spawn` does not return an instance of the `ChildProcess` class.

**Comment by Massolari** [comment]
@CrowdHailer 
Right, I'll change the approach. I did this way based on the README
> The aim of this package is to not make any new abstractions, so binding are as near the native platform as is sensible.

But I also like to have a more functional way


> this is an incorrect definition even if you want to use the OOP design. child_process.spawn does not return an instance of the ChildProcess class

@lpil 
Oops! Maybe I'm missing something. I took this signature from the Node.js documentation: https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

On [Child's Process](https://nodejs.org/api/child_process.html#class-childprocess) documentation it's also written about `spawn`:
> Instances of ChildProcess are not intended to be created directly. Rather, use the child_process.spawn()

Could you point me out to the correct return type?

**Comment by lpil** [comment]
It's externally defined and doesn't subclass the Gleam record class, so you'd need to use an external type to indicate that it is externally defined and not defined in Gleam.

```gleam
pub type ChildProcess
```

**Comment by Massolari** [comment]
@lpil But if I define it like that, how would I be able to access its properties, like `stdin`?
I would to create a function `stdin(child_process: ChildProcess) -> Stdin` and make a FFI call, I'm not sure if this is the best approach since it would be necessary to any other property 🤔

**Comment by Massolari** [comment]
@CrowdHailer `kill` is now a public function of the module instead of a "method"

**Comment by lpil** [comment]
> @lpil But if I define it like that, how would I be able to access its properties, like stdin?

Gleam cannot directly access properties on objects defined outside of Gleam.

**Comment by Massolari** [comment]
Done!
Now there is a `stdin` function that returns `Result(stream.Writable, Nil)`

**Comment by CrowdHailer** [comment]
looks good. Thanks for perservering

**Pull request merged**
